version: "3.8"
services:
  api:
    build: .
    restart: always
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    driver: bridge